web:
  image: stevesloka/k8s-webapp
  volumes:
    - /vagrant/devopsdays/webapp/dist:/usr/share/nginx/html
  links:
    - api
  ports:
    - "80:80"
  environment:
    API_SERVICE_HOST: api
    API_SERVICE_PORT: 8080
api:
  image: stevesloka/k8s-api
  ports:
    - "8080:8080"
  links:
    - db
  environment:
    spring.datasource.url: jdbc:mysql://db/demo_db
db:
  image: stevesloka/k8s-mysql
