api: 
  image: stevesloka/k8s-api
  ports:
    - "8080:8080"
  links:
    - db
  environment:
    spring.datasource.url: jdbc:mysql://db/demo_db
    #hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
db:
  image: stevesloka/k8s-mysql
