web:
  image: stevesloka/k8s-webapp:develop
  volumes:
    - ./webapp/dist:/usr/share/nginx/html
  links:
    - api
  ports:
    - "80:80"
  environment:
    API_SERVICE_HOST: api
    API_SERVICE_PORT: 8080
api:
  image: stevesloka/api:develop
  ports:
    - "8080:8080"
  links:
    - db
  environment:
    spring.datasource.url: jdbc:mysql://db/demo_db
db:
  image: stevesloka/db:develop
