api: 
  image: stevesloka/k8s-api
  ports:
    - "8080:8080"
  links:
    - db
  environment:
    #spring.datasource.url: jdbc:mysql://db:3307/demo_db
db:
  image: stevesloka/k8s-mysql
  ports:
    - "3307:3306"
