apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-v1.0
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: api
        version: "1.0"
    spec:
      containers:
      - name: api
        image: stevesloka/api
        ports:
        - containerPort: 8080
        env:
          - name: spring_datasource_url
            value: jdbc:mysql://db/demo_db
