apiVersion: v1
kind: ReplicationController
metadata:
  name: update-demo-kitten
  labels:
    visualize: "true"
spec:
  selector:
    name: update-demo
    version: kitten
  template:
    metadata:
      labels:
        name: update-demo
        version: kitten
        visualize: "true"
    spec:
      containers:
      - image: stevesloka/update-demo:kitten
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP
